# ESTÁGIO 1: Construção (Onde compilamos o pgvector)
FROM postgres:15 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-15-postgis-3 \
    build-essential \
    postgresql-server-dev-15 \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L https://github.com/pgvector/pgvector/archive/refs/tags/v0.8.0.tar.gz -o pgvector.tar.gz && \
    tar -xzf pgvector.tar.gz && \
    cd pgvector-0.8.0 && make && make install

# ESTÁGIO 2: Final (Imagem limpa para o servidor ARM)
FROM postgres:15

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-15-postgis-3 \
    && rm -rf /var/lib/apt/lists/*

# Pegamos apenas os arquivos prontos da etapa anterior
COPY --from=builder /usr/lib/postgresql/15/lib/vector.so /usr/lib/postgresql/15/lib/
COPY --from=builder /usr/lib/postgresql/15/share/extension/vector* /usr/lib/postgresql/15/share/extension/

COPY init.sql /docker-entrypoint-initdb.d/
